const WaveDivider = () => {
  return (
    //   Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections
    //   Refactored for Tailwind

    <div className="h-[150px] overflow-hidden">
      <svg
        viewBox="0 0 500 150"
        preserveAspectRatio="none"
        className="h-full w-full stroke-0 fill-primaryDarker"
      >
        <path d="M0.00,116.95 C149.99,150.00 271.49,-49.98 500.56,105.11 L500.00,0.00 L0.00,0.00 Z"></path>
      </svg>
    </div>
  );
};

export default WaveDivider;
